name: Build Test and Release

on:
  push:
    paths-ignore: [docs/**, README.md, examples/**]
    branches: [ 0.4.X.X ]
  pull_request:
    branches: [ 0.4.X.X ]
jobs:
  # ----------------------------------
  # BUILD
  # ----------------------------------
  build:
    name: Build on Python ${{matrix.python_version}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ['3.7.x', '3.8.x', '3.9.x']
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Setup Python ${{matrix.python_version}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python_version}}
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools wheel
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build artifact
      run: python setup.py sdist bdist_wheel

  # -----------------------------------
  # Turn on ENV
  # -----------------------------------
  turn-on-env:
    name: Turn on test environment
    runs-on: ubuntu-latest
    env:
      TPLINK_USER: ${{ secrets.TPLINK_USER }}
      TPLINK_PASS: ${{ secrets.TPLINK_PASS }}
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2-beta
        with:
          node-version: 11.x
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          pushd ext-res/tests
          npm install 
          popd
      - name: Powering on the dev-environment
        run: |
          pushd ext-res/tests
          node ./switch.js --dev MEROSS_LAB --toggle=on
          popd

  # ---------------------------------
  # Testing
  # ---------------------------------
  test:
    name: Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ['3.7', '3.8', '3.9']
      max-parallel: 1
    outputs:
      success_rate_python_3_7: 0
      success_rate_python_3_8: 0
      success_rate_python_3_9: 0
    needs: [build, turn-on-env]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python ${{matrix.python_version}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{matrix.python_version}}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest --upgrade
        pip install pytest-html --upgrade
        pip install pytest-cov --upgrade
        pip install pytest-json-report --upgrade
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Wait a bit before running tests
      run: |
        echo "Waiting 120 seconds before starting..."
        sleep 120
        echo "Waiting done."
    - name: Test with pytest
      env:
        MEROSS_EMAIL: ${{ secrets.MEROSS_EMAIL }}
        MEROSS_PASSWORD: ${{ secrets.MEROSS_PASSWORD }}
      run: |
        pip install .
        # Set credentials into memory
        TOKEN=$(meross_api_cli auth login --email $MEROSS_EMAIL --password "$MEROSS_PASSWORD" | base64 -w0)
        # Run test
        __MEROSS_CREDS=$TOKEN pytest tests --json-report --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=xml --cov-report=html --html=junit/test-results.html --self-contained-html
        # Invalidate token
        __MEROSS_CREDS=$TOKEN meross_api_cli auth logout
        # Parse test outcomes
        total_tests=`cat .report.json | jq .summary.total`
        passed_tests=`cat .report.json | jq .summary.passed`
        failed_tests=`cat .report.json | jq .summary.failed`
        success_rate=`echo $passed_tests/$total_tests*100 | bc -l`
        echo "::set-output name=success_rate::$success_rate"
      continue-on-error: true
    - name: Upload pytest test results
      uses: actions/upload-artifact@v2
      with:
        name: pytest-results
        path: junit/
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}

    - name: Upload pytest test results
      uses: actions/upload-artifact@v2
      with:
        name: pytest-results-html
        path: htmlcov/
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}

  # ------------------------------
  # Turn off ENV
  # ------------------------------
  turn-off-env:
    name: Turn off test environment
    runs-on: ubuntu-latest
    needs: [test]
    env:
      TPLINK_USER: ${{ secrets.TPLINK_USER }}
      TPLINK_PASS: ${{ secrets.TPLINK_PASS }}
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2-beta
        with:
          node-version: 11.x
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          pushd ext-res/tests
          npm install 
          popd
      - name: Powering on the dev-environment
        run: |
          pushd ext-res/tests
          node ./switch.js --dev MEROSS_LAB --toggle=off
          popd
    if: ${{ always() }}
    
  # -----------------------------
  # Build and Release
  # -----------------------------
  release:
    runs-on: ubuntu-latest
    needs: [test, build]
    if: jobs.test.outputs.success_rate_python_3_7 > 60 && jobs.test.outputs.success_rate_python_3_8 > 60 jobs.test.outputs.success_rate_python_3_9 > 60
    steps:
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/checkout@v2
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U setuptools wheel
          pip install twine
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build artifact
        run: python setup.py sdist bdist_wheel --universal
      - name: Calculate Version
        id: tag
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        run: |
          TAG=$(cat $GITHUB_WORKSPACE/.version)
          echo "Tag: $TAG"
          echo "tag=$TAG" >> $GITHUB_ENV
      - name: Release on GitHub
        uses: actions/create-release@v1
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
         tag_name: ${{env.tag}}
         release_name: Version ${{env.tag}}
      - name: Release on Pypi
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: |
          twine upload -u "$TWINE_USERNAME" -p "$TWINE_PASSWORD" dist/*
